%% Setup file
[p1, ~, ~] = fileparts(mfilename('fullpath'));
cd(p1);

%% Run external setup files
run(fullfile(p1, 'extern', 'SmallRotationToolbox', 'setup.m'));

%% Adds the necessary folders to path
addpath(p1);
dirs = {'alignment', ...
    'clebsch_gordan', ...
    'compactification', ...
    'estimation', ...
    'image_generation', ...
    'inversion', ...
    'spherical_harmonics', ...
    'spherical_spectra', ...
    't_design'};
for J=1:length(dirs)
    addpath(genpath(fullfile(p1, dirs{J})));
end
