#Compilation variables
CC=gcc
MATLABFAGS=-R2018a
MEX=mex.bat
OUTDIRCMD=-o

#Include directory variables
SMFTDir=extern/SFMT
ROTATIONSAMPLINGDir=extern/RotationSampling
ALIGNMENTDir=alignment
CGDir=clebsch_gordan
ESTIMATIONDir=estimation
INVERSIONDir=
SHDir=spherical_harmonics
SPECTRADir=spherical_spectra
TDESIGNDir=tdesign

#Output directory variables
MEXOUTDIR=bin/mex
TESTEROUTDIR=bin/testers